export enum SystemRequest {
  Handshake= 0,
  Login= 1,
  Logout= 2,
  GetRoomList= 3,
  JoinRoom= 4,
  AutoJoin= 5,
  CreateRoom= 6,
  GenericMessage= 7,
  ChangeRoomName= 8,
  ChangeRoomPassword= 9,
  ObjectMessage= 10,
  CallExtension= 13,
  LeaveRoom= 14,
  SpectatorToPlayer= 17,
  PlayerToSpectator= 18,
  PublicMessage= 20,
  PrivateMessage= 21,
  AdminMessage= 23,
  KickUser= 24,
  BanUser= 25,
  FindRooms= 27,
  FindUsers= 28,
  PingPong= 29,
  Disconnect=30
}
